### ISSUE TITLE
Breaking change in v2 related to non-F# objects?

### ISSUE THREAD

**Issue by matthid** [elmish/debugger#20]
### Description

I have not quite debugged our issue but I feel like the upgrade to fable 2 broke the debugger for us

### Repro code

This is a bit hard because basically what we do is embed TypeScript "elmish" components (basically `update`/`view`/`init` written in typescript) into our fable emlish application. This worked fine.

The problem I see is this:
![image](https://user-images.githubusercontent.com/1866463/53036361-de7d0a80-3477-11e9-963c-cd39fec50a92.png)

![image](https://user-images.githubusercontent.com/1866463/53036409-fce30600-3477-11e9-8b3d-be71ee1f43d9.png)

![image](https://user-images.githubusercontent.com/1866463/53036450-15ebb700-3478-11e9-852d-5d712ff4a0b7.png)

The parameter seems to originate from the following Typescript definition:

```typescript
type Msg =
    { type: "LanguageMapping", translations: object } |
    { type: "GetInstanceName", name: string | undefined } |
    { type: "TestConnectionAvailable" } |
    { type: "ConnectionAvailable", available: boolean } |
    ... several other cases left out ...;
```

### Expected and actual results

Expected: Debugger can work with non-F# objects
Actual: Debugger fails

### Related information 

* elmish version: `Fable.Elmish (2.0.3)`
* fable-compiler version: `"fable-compiler": { "version": "2.1.10",`
* fable-core version: `Fable.Core (2.0.3)`
* Operating system: Win 7 (I know but I'm pretty sure it is not related to the OS)

**Comment by MangelMaxime** [comment]
The debugger is now using Thoth.Json as Fable 2 removed `toJson` and `ofJson`.

Because the debugger is also using version 2 of Thoth.Json if it doesn't understand the type it will generate an error.

Thoth.Json isn't able to serialize/deserialize an unknown type. However, in version 3 of Thoth.Json, we added the possibility to extends the known types by Thoth.Json [docs](https://mangelmaxime.github.io/Thoth/json/v3.html#extra-coders).

I don't know if this is possible to extend it in order to support non F# types. Perhaps, by defining a binding for the type it can be possible or perhaps I need to allow adding non F# type support to Thoth.Json with the limitation that the type is identifiable using `typeof` or a `test` function. In the case of your type, the test function would check for `type` property for example.

I didn't release Thoth.Json v3 yet because I didn't get a lot of feedback on it. And wanted to finish the docs upgrade.

As a quick fix, I think you will need to copy the `debugger` function and use Thoth.Json v3 to check if you can deserialize `TypeScript` types.

**Comment by matthid** [comment]
Hm, maybe then Thoth is just no applicable for us and we need a way to opt-out and use normal Js-object -> Json serialization?

I can try to find a workaround where I use Thoth for fable components and use "simple" js serialization for typescript components

**Comment by et1975** [comment]
If you can think of a sensible extensibility point for the debugger to take
the serializer that would be great too.

**Comment by matthid** [comment]
@MangelMaxime apparently this wasn't an issue with Thoth after all. There was just code added which assumed that the type is a F#-DU which it obviously isn't in my scenario...

**Comment by MangelMaxime** [comment]
Good catch :)
