### ISSUE TITLE
remotedevtools has security vulnerability

### ISSUE THREAD

**Issue by Larocceau** [elmish/debugger#64]
The remoteDev NPM package has a security vulnerability, and this tool depends on it.
See also https://github.com/SAFE-Stack/SAFE-template/issues/602

**Comment by MangelMaxime** [comment]
Hello,

We can't do anything about it.

There is [this issue](https://github.com/zalmoxisus/remotedev/issues/23) which track the security issue on the remotedev repository. But the package didn't receive an update in 5 year, so it is unlikely to be fixed I think.

Because, this should be used in as a dev dependency only it should be ok to still use it.

**Comment by et1975** [comment]
Another reason to address #7 and have the debugger client re-implemented in F#.
